###
# ###: request delimiters
# Syntax: POST [location specified in @app.post]
POST http://localhost:8000/fruits
Content-Type: application/json

{
    "name": "Pear"
}

###
# GET requests can be implemented too:
GET http://localhost:8000/fruits
Accept: application/json 